env:
  global:
  - secure: EIQ8VWbg8LRnX7n6PIP9HjXLg4nIKOsJk0xnMunbMZ475Z+pTd73awLu6VCbjO5DVAd9R7W36snIlGVv92j3dai6e0jOO+WtSTQ7gd1cEq+4swEXg7Qvc1oyqsXVL+FoO+j1InZxxUx93ObLRGvFZiUeBhnPNdqsM794EkUScN4=
  - secure: HLMEzx4NuU+oXU5yGViN8pAfFvhVeib5zvfH21nVbOC1Rg57HUKQTRCg5S/acr5C8At4BfHORt7p3MHztGB/GXylzm1kFRnKliJ50S9BkEW+/852f2gbGmnIEe7aMz4nFOheRpLgk7zcZrbYbztoRAFL+HREBiEaAZu8bti4gpU=
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: java
jdk:
- oraclejdk11

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/31a671345ecfdce18046
    on_success: change
    on_failure: always
    on_start: never
before_install:
- pip install --user codecov
- sudo dpkg --purge --force-depends ca-certificates-java
- sudo apt-get install ca-certificates-java
- sudo update-ca-certificates -f
install: "./gradlew assemble -DexcludeBenchmark"
script: "./gradlew check -DexcludeBenchmark"
after_success:
- "./gradlew buildDistributions -DexcludeBenchmark"
- codecov
deploy:
  provider: bintray
  file: "bintray.json"
  user: "jbachorik"
  key:
    secure: I+Lvki1TM2pQPJEf75U098GSQexgjudOZ2TDCPSQEdGys7PdW7SIy5THiHYdCG+tO8dSKQ3FUXufDD1KzhHxEBSWUX1rpAgE3SGvxYwzAU+bl3FvoQzjb+WD69ya86h0TFM2fVOJsg4+iDimheHcD+7mCuYx3ga1dsi8lVjh38s=
  on:
    branch: master
    condition: ${TRAVIS_JDK_VERSION} == oraclejdk8
